CREATE TABLE vijesti (
  id INT PRIMARY KEY AUTO_INCREMENT,
  naslov VARCHAR(255),
  tekst TEXT,
  sazetak TEXT,
  kategorija VARCHAR(50),
  slika VARCHAR(50),
  arhivirano BOOLEAN,
  datum DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE kategorije (
  id INT PRIMARY KEY AUTO_INCREMENT,
  naziv VARCHAR(50)
);
INSERT INTO kategorije (naziv) VALUES
  ('Parisien'),
  ('Vivre Mieux');
  
CREATE TABLE korisnik (
  id INT PRIMARY KEY AUTO_INCREMENT,
  korisnicko_ime VARCHAR(50) UNIQUE,
  lozinka VARCHAR(255),
  administratorska_prava BOOLEAN
);
INSERT INTO vijesti (id, naslov, tekst, sazetak, kategorija, arhivirano, slika)
VALUES
    (1, 'Nouveau restaurant français ouvre ses portes', 'Le nouveau restaurant français, Le Petit Bistro, a ouvert ses portes aujourd\'hui. Situé au cœur de la ville, ce charmant établissement offre une expérience culinaire authentique. Les clients peuvent déguster une délicieuse cuisine française préparée par des chefs renommés. Les plats sont préparés avec des ingrédients frais et locaux, mettant en valeur les saveurs et les traditions de la cuisine française. Le Petit Bistro propose également une sélection raffinée de vins français pour accompagner chaque repas. Venez découvrir ce nouveau joyau gastronomique de la ville et laissez-vous séduire par son ambiance chaleureuse et son menu exquis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel mi malesuada, lacinia est eu, eleifend quam. Aliquam viverra pharetra iaculis. Donec ut scelerisque turpis, id molestie eros. Nulla vestibulum risus a nisi efficitur, et semper dui tristique. Vestibulum varius augue vel lectus egestas, sit amet hendrerit tellus condimentum. Donec pretium purus nec posuere condimentum. Duis quis enim elementum, gravida tellus vitae, tincidunt nunc. Aliquam ac fermentum sem. Donec et erat et metus lobortis pretium. Nunc fermentum magna ut orci pellentesque, sit amet euismod lacus ullamcorper. Donec vitae neque pulvinar, euismod dolor ac, malesuada odio.', 'Un nouveau restaurant français a ouvert ses portes au cœur de la ville. Venez déguster une cuisine authentique préparée par des chefs renommés.', 'Parisien', 0, 'slike/slika1.webp'),
    (2, 'Exposition d\'art moderne au Musée de Paris', 'Le Musée de Paris accueille une exposition d\'art moderne mettant en vedette les œuvres des artistes les plus influents de notre époque. L\'exposition présente une variété de médiums artistiques, tels que la peinture, la sculpture, la photographie et l\'installation. Chaque œuvre raconte une histoire unique et offre une perspective nouvelle sur l\'art moderne. Les visiteurs auront l\'occasion de découvrir des créations fascinantes et d\'explorer les tendances actuelles de l\'art contemporain. Ne manquez pas cette exposition incontournable qui célèbre la créativité et l\'expression artistique. Sed vulputate arcu ac justo interdum, in dapibus ex finibus. Maecenas efficitur dapibus sapien, at tristique velit convallis vitae. Curabitur varius sagittis neque, vitae suscipit justo vulputate sed. Ut at mi massa. Aliquam erat volutpat. Quisque a iaculis nisl. Fusce ut congue metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 'Le Musée de Paris présente une exposition d\'art moderne avec des œuvres uniques des artistes les plus influents.', 'Parisien', 0, 'slike/slika2.jpeg'),
    (3, 'Conseils pour une vie saine et équilibrée', 'Découvrez quelques conseils simples pour mener une vie saine et équilibrée. Commencez par adopter une alimentation équilibrée et variée, riche en fruits, légumes et protéines maigres. Faites de l\'exercice régulièrement en choisissant une activité physique qui vous plaît, comme la marche, la natation ou le yoga. Prenez également le temps de vous détendre et de gérer le stress avec des techniques de relaxation telles que la méditation ou la respiration profonde. Enfin, n\'oubliez pas de dormir suffisamment pour permettre à votre corps de se reposer et de se régénérer. En suivant ces conseils, vous vous sentirez plus énergique, plus équilibré et plus épanoui dans votre vie quotidienne. Sed vulputate mi eget ullamcorper viverra. Pellentesque porta ullamcorper purus, vel porta odio iaculis a. Integer rhoncus velit non est varius, et tempus ligula consectetur. Integer sed ligula iaculis, suscipit orci vitae, finibus velit. Sed ac scelerisque dui. Integer accumsan dignissim risus, in vestibulum metus mattis vitae. Quisque accumsan tortor id ex lacinia dignissim. Morbi tempor posuere mi nec pellentesque. Suspendisse auctor cursus lorem vitae pharetra.', 'Découvrez des conseils pour mener une vie saine et équilibrée, du régime alimentaire à l\'exercice physique.', 'Parisien', 0, 'slike/slika3.jpg'),
    (4, 'Nouveaux looks de mode pour la saison printemps-été', 'Découvrez les nouveaux looks de mode pour la saison printemps-été. Les couleurs vives et les imprimés audacieux sont à l\'honneur cette année. Des robes légères et fluides aux combinaisons colorées, il y en a pour tous les goûts. Les accessoires jouent également un rôle important, avec des sacs à main et des chaussures qui complètent parfaitement chaque tenue. Laissez-vous inspirer par ces nouvelles tendances et créez des looks uniques pour les mois à venir. Quisque aliquam magna non metus vestibulum rutrum. Nam id convallis ex. Ut vitae risus neque. Curabitur at ultricies metus. Sed tempus vestibulum justo ac fringilla. Integer ut dui eu justo placerat semper. Fusce ut varius mi. Fusce in lorem dapibus, volutpat purus ut, elementum tellus. Integer nec finibus nisi, sit amet iaculis mauris. Morbi vulputate felis sapien, ac posuere odio sagittis vitae. Nullam sit amet nibh id nisi mollis sagittis sit amet a augue.', 'Découvrez les nouvelles tendances de mode pour la saison printemps-été et soyez à la pointe de la mode.', 'Vivre Mieux', 0, 'slike/slika4.jpeg'),
    (5, 'Les meilleurs endroits pour se détendre et se ressourcer', 'Découvrez les meilleurs endroits pour se détendre et se ressourcer. Des spas luxueux aux retraites tranquilles en pleine nature, ces destinations vous offriront des moments de détente et de bien-être. Profitez de massages apaisants, de bains relaxants et de soins revitalisants dans des environnements sereins. Que vous recherchiez une escapade romantique ou une pause bien méritée en solo, ces endroits vous offriront une expérience inoubliable. Sed malesuada ex nec purus vestibulum aliquam. Vestibulum et facilisis risus. Maecenas lacinia malesuada tellus eu malesuada. Aliquam congue enim vel ultricies iaculis. Cras quis posuere turpis, eu gravida odio. Nullam tincidunt nisi at augue interdum, ac congue felis gravida.', 'Découvrez les meilleurs endroits pour vous détendre et vous ressourcer, des spas luxueux aux retraites tranquilles en pleine nature.', 'Vivre Mieux', 0, 'slike/slika5.webp'),
    (6, 'Les secrets d\'une alimentation saine et équilibrée', 'Découvrez les secrets d\'une alimentation saine et équilibrée pour maintenir votre santé et votre bien-être. Consommez une variété d\'aliments frais et colorés, tels que des fruits, des légumes, des céréales complètes et des protéines maigres. Évitez les aliments transformés riches en sucres ajoutés et en matières grasses saturées. Optez pour des alternatives plus saines, comme les snacks de fruits secs et les produits laitiers faibles en gras. Assurez-vous de rester hydraté en buvant suffisamment d\'eau tout au long de la journée. En adoptant ces habitudes alimentaires, vous favoriserez votre santé globale et vous vous sentirez mieux au quotidien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur suscipit ligula, eu commodo dui pellentesque sed. Nam ac justo quis lorem fermentum elementum sed et enim. In auctor purus sed arcu efficitur, vel ultrices nisi efficitur.', 'Découvrez les secrets d\'une alimentation saine et équilibrée pour maintenir votre santé et votre bien-être.', 'Vivre Mieux', 0, 'slike/slika6.png');

ALTER TABLE korisnik
ADD ime VARCHAR(255) NOT NULL AFTER korisnicko_ime,
ADD prezime VARCHAR(255) NOT NULL AFTER ime`vijesti`;

INSERT INTO korisnik (ime, prezime, korisnicko_ime, lozinka, administratorska_prava) VALUES
('Mia', 'Sykora', 'msykora', '3884', 1),('Marko', 'Jurić', 'mjuric', '1111', 0), ('Ana', 'Novak', 'anovak', '2222',0),('Ivan', 'Horvat', 'ihorvat', '3333',0);
